name: Compute and verify vendor SHA256

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  compute-sha256:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Compute SHA256s
        run: npm run sha256
      - name: Upload SHA256 manifest
        uses: actions/upload-artifact@v4
        with:
          name: libs-with-sha256
          path: libs-with-sha256.json